name: borizjersey
favicon: null
layout_spectrum: 0.28512
typography_spectrum: 0.26693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74221b'
    - '#ffffff'
    - '#c3933a'
    - '#84652e'
    - '#ecc552'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
