name: borizjersey
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74221a'
    - '#acacac'
    - '#fefefe'
    - '#c39239'
    - '#717171'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
